### ISSUE TITLE
Conda Package 19.7 is not installing incremental dependency

### ISSUE THREAD

**Issue by swainn** [conda-forge/twisted-feedstock#11]
Issue:

Installed new environment with twisted:

```bash
conda create -n twisted twisted
```
Any import from twisted fails with this error:
```python
from twisted import *

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/swainn/miniconda3/envs/twisted/lib/python3.7/site-packages/twisted/__init__.py", line 11, in <module>
    from twisted._version import __version__ as version
  File "/home/swainn/miniconda3/envs/twisted/lib/python3.7/site-packages/twisted/_version.py", line 8, in <module>
    from incremental import Version
ModuleNotFoundError: No module named 'incremental'
```

Inspecting the environment (below) reveals that incremental is not installed. As a side note, installing version `twisted` 19.2 does install incremental.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/swainn/miniconda3/envs/twisted:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
asn1crypto                0.24.0                py37_1003    conda-forge
attrs                     19.1.0                     py_0    conda-forge
bcrypt                    3.1.6            py37h516909a_1    conda-forge
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
cffi                      1.12.3           py37h8022711_0    conda-forge
cryptography              2.7              py37h72c5cf5_0    conda-forge
idna                      2.8                   py37_1000    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pip                       19.2.1                   py37_0    conda-forge
pyasn1                    0.4.6                      py_0    conda-forge
pyasn1-modules            0.2.6                      py_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
service_identity          18.1.0                     py_0    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.29.0               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
twisted                   19.7.0           py37h516909a_0    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info


  active environment : twisted
    active env location : /home/swainn/miniconda3/envs/twisted
            shell level : 2
       user config file : /home/swainn/.condarc
 populated config files : /home/swainn/.condarc
          conda version : 4.6.8
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /home/swainn/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/swainn/miniconda3/pkgs
                          /home/swainn/.conda/pkgs
       envs directories : /home/swainn/miniconda3/envs
                          /home/swainn/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.7.1 Linux/4.18.0-25-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by msouff** [comment]
It's not only incremental, none of the listed twisted dependencies are being installed.

```
requirements = [
    "zope.interface >= 4.4.2",
    "constantly >= 15.1",
    "incremental >= 16.10.1",
    "Automat >= 0.3.0",
    "hyperlink >= 17.1.1",
    "PyHamcrest >= 1.9.0",
    "attrs >= 17.4.0",
]
```

From: https://github.com/twisted/twisted/blob/trunk/src/twisted/python/_setup.py#L282-L290

**Comment by ocefpaf** [comment]
The regeneration script I used missed those :-/
In the script defense `src/twisted/python/_setup.py` is not a trivial place to declare dependencies ;-p

Does any of you want to send a PR to fix that?

**Comment by swainn** [comment]
@ocefpaf I'm not sure that I follow. The dependencies are all listed in the `meta.yml` and it doesn't look much different from the previous version, which seemed to be working. Does the regeneration script pull the dependencies from the `setup.py` instead of the recipe?

**Comment by isuruf** [comment]
@jjhelmus, @mbargull, is it a known bug that if a dependency appears in both `run` and `run_constrained`, then the dependency is treated only as a `run_constrained`?

**Comment by jjhelmus** [comment]
> is it a known bug that if a dependency appears in both `run` and `run_constrained`, then the dependency is treated only as a `run_constrained`

I believe conda is fine with requirements that appear in both run (dependencies) and run_constrained (constraints).  From the package information it looks like requirements appearing in both sections end up in only one section in the final package:

```
(base) ~$ tar xf ~/Downloads/twisted-19.7.0-py36h516909a_0.tar.bz2 info/index.json -O
{
  "arch": "x86_64",
  "build": "py36h516909a_0",
  "build_number": 0,
  "constrains": [
    "python",
    "attrs >=17.4.0",
    "automat >=0.3.0",
    "constantly >=15.1",
    "hyperlink >=17.1.1",
    "incremental >=16.10.1",
    "pyhamcrest >=1.9.0",
    "zope.interface >=4.4.2",
    "pyserial >=3.0",
    "h2 >=3.0,<4.0",
    "priority >=1.1.0,<2.0"
  ],
  "depends": [
    "attrs >=17.4.0",
    "automat >=0.3.0",
    "bcrypt",
    "constantly >=15.1",
    "cryptography >=1.5",
    "hyperlink >=17.1.1",
    "idna >=0.6,!=2.3",
    "incremental >=16.10.1",
    "libgcc-ng >=7.3.0",
    "pip",
    "pyasn1",
    "pyhamcrest >=1.9.0",
    "pyopenssl >=16.0.0",
    "python >=3.6,<3.7.0a0",
    "service_identity >=18.1.0",
    "zope.interface >=4.4.2"
  ],
  "license": "MIT",
  "license_family": "MIT",
  "name": "twisted",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1565107205936,
  "version": "19.7.0"
```

`conda-build` might be doing something unusual here with the repeated dependencies.  Is there a reason to put these in both sections?  If these two section are identical then the `run_constrained` section is not needed since the requirements are enforced explicitly.

**Comment by isuruf** [comment]
> Is there a reason to put these in both sections?

No, I think @ocefpaf's script was misbehaving when these packages were added.

Note that `incremental` is in both sections

**Comment by ocefpaf** [comment]
> Note that incremental is in both sections

Yep. It copied things from `run`. I never run this script on a recipe with `run_constrained`` before. Good to know that it is completely broken :smile:

**Comment by swainn** [comment]
@ocefpaf I have confirmed that #12 fixes this issue. Thanks for the quick response!
